'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

'Imports System
'Imports System.ComponentModel
'Imports System.Diagnostics
'Imports System.Web.Services
'Imports System.Web.Services.Protocols
'Imports System.Xml.Serialization

'''<remarks>
'''This source code was auto-generated by wsdl, Version=2.0.50727.42.
'''</remarks>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Web.Services.WebServiceBindingAttribute(Name:="ValidatorSoap", [Namespace]:="http://validate-epa.std/")> _
Partial Public Class Validator
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

    Private validate_mpOperationCompleted As System.Threading.SendOrPostCallback

    Private validate_epaOperationCompleted As System.Threading.SendOrPostCallback

    Private date_changedOperationCompleted As System.Threading.SendOrPostCallback

    '''<remarks/>
    Public Sub New()
        MyBase.New()
        Me.Url = My.Settings.ValidationURL
    End Sub

    '''<remarks/>
    Public Event validate_mpCompleted As validate_mpCompletedEventHandler

    '''<remarks/>
    Public Event validate_epaCompleted As validate_epaCompletedEventHandler

    '''<remarks/>
    Public Event date_changedCompleted As date_changedCompletedEventHandler

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://validate-epa.std/validate_mp", RequestNamespace:="http://validate-epa.std/", ResponseNamespace:="http://validate-epa.std/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function validate_mp(ByVal inxml As String) As String
        Dim results() As Object = Me.Invoke("validate_mp", New Object() {inxml})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function Beginvalidate_mp(ByVal inxml As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("validate_mp", New Object() {inxml}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function Endvalidate_mp(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub validate_mpAsync(ByVal inxml As String)
        Me.validate_mpAsync(inxml, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub validate_mpAsync(ByVal inxml As String, ByVal userState As Object)
        If (Me.validate_mpOperationCompleted Is Nothing) Then
            Me.validate_mpOperationCompleted = AddressOf Me.Onvalidate_mpOperationCompleted
        End If
        Me.InvokeAsync("validate_mp", New Object() {inxml}, Me.validate_mpOperationCompleted, userState)
    End Sub

    Private Sub Onvalidate_mpOperationCompleted(ByVal arg As Object)
        If (Not (Me.validate_mpCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent validate_mpCompleted(Me, New validate_mpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://validate-epa.std/validate_epa", RequestNamespace:="http://validate-epa.std/", ResponseNamespace:="http://validate-epa.std/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function validate_epa(ByVal inxml As String) As String
        Dim results() As Object = Me.Invoke("validate_epa", New Object() {inxml})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function Beginvalidate_epa(ByVal inxml As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("validate_epa", New Object() {inxml}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function Endvalidate_epa(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub validate_epaAsync(ByVal inxml As String)
        Me.validate_epaAsync(inxml, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub validate_epaAsync(ByVal inxml As String, ByVal userState As Object)
        If (Me.validate_epaOperationCompleted Is Nothing) Then
            Me.validate_epaOperationCompleted = AddressOf Me.Onvalidate_epaOperationCompleted
        End If
        Me.InvokeAsync("validate_epa", New Object() {inxml}, Me.validate_epaOperationCompleted, userState)
    End Sub

    Private Sub Onvalidate_epaOperationCompleted(ByVal arg As Object)
        If (Not (Me.validate_epaCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent validate_epaCompleted(Me, New validate_epaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://validate-epa.std/date_changed", RequestNamespace:="http://validate-epa.std/", ResponseNamespace:="http://validate-epa.std/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function date_changed() As String
        Dim results() As Object = Me.Invoke("date_changed", New Object(-1) {})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function Begindate_changed(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("date_changed", New Object(-1) {}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function Enddate_changed(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub date_changedAsync()
        Me.date_changedAsync(Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub date_changedAsync(ByVal userState As Object)
        If (Me.date_changedOperationCompleted Is Nothing) Then
            Me.date_changedOperationCompleted = AddressOf Me.Ondate_changedOperationCompleted
        End If
        Me.InvokeAsync("date_changed", New Object(-1) {}, Me.date_changedOperationCompleted, userState)
    End Sub

    Private Sub Ondate_changedOperationCompleted(ByVal arg As Object)
        If (Not (Me.date_changedCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent date_changedCompleted(Me, New date_changedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
Public Delegate Sub validate_mpCompletedEventHandler(ByVal sender As Object, ByVal e As validate_mpCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class validate_mpCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
Public Delegate Sub validate_epaCompletedEventHandler(ByVal sender As Object, ByVal e As validate_epaCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class validate_epaCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
Public Delegate Sub date_changedCompletedEventHandler(ByVal sender As Object, ByVal e As date_changedCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class date_changedCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class
